<p style="font-family: Arial; font-size:3em;color:black;"> Session 4 - Lab Exercise 8</p>

## Name: Iretioluwa Olawuyi

We will use the titanic dataset from Kaggle (https://www.kaggle.com/). This is a well-known dataset and we will use it for classification- if the passenger survived or passed away.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
training_DF = pd.read_csv('data/titanic_dataset_GBC.csv')

In [3]:
training_DF['Age'].fillna(training_DF['Age'].mean(), inplace=True)

In [4]:
training_DF.drop('Cabin',axis=1,inplace=True)

In [5]:
training_DF.dropna(inplace=True)

In [6]:
sex = pd.get_dummies(training_DF['Sex'])
embark = pd.get_dummies(training_DF['Embarked'])

In [7]:
training_DF.drop(['Sex','Embarked','Name','Ticket'],axis=1,inplace=True)

In [8]:
training_DF = pd.concat([training_DF,sex,embark],axis=1)

In [9]:
training_DF.drop(['female','C'],axis=1,inplace=True)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(training_DF.drop('Survived',axis=1), 
                                                    training_DF['Survived'], test_size=0.30, 
                                                    random_state=101)

In [12]:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)

In [57]:
# let's explore SGDClassifier parameters

'''
SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)
'''

# Let's form SGD models with variation in paameters loss and alpha
    # loss: 'hinge', 'log', and 'modified_huber'
    # alpha: 0.0001 and 0.001
    # explain and dicuss your findings

In [17]:
from sklearn.metrics import confusion_matrix, classification_report

In [18]:
# Case 1 - loss: 'hinge', alpha: 0.0001
model = \
    SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_pred, y_test))

print(classification_report(y_pred, y_test))

[[85 48]
 [78 56]]
              precision    recall  f1-score   support

           0       0.52      0.64      0.57       133
           1       0.54      0.42      0.47       134

    accuracy                           0.53       267
   macro avg       0.53      0.53      0.52       267
weighted avg       0.53      0.53      0.52       267



c:\Users\ireti\Documents\GBC\AASD 4000\env\lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [19]:
# Case 2 - loss: 'log', alpha: 0.001
model = \
    SGDClassifier(
    loss='log',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_pred, y_test))

print(classification_report(y_pred, y_test))

[[71 43]
 [92 61]]
              precision    recall  f1-score   support

           0       0.44      0.62      0.51       114
           1       0.59      0.40      0.47       153

    accuracy                           0.49       267
   macro avg       0.51      0.51      0.49       267
weighted avg       0.52      0.49      0.49       267



c:\Users\ireti\Documents\GBC\AASD 4000\env\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:165: FutureWarning: The loss 'log' was deprecated in v1.1 and will be removed in version 1.3. Use `loss='log_loss'` which is equivalent.
  warnings.warn(
c:\Users\ireti\Documents\GBC\AASD 4000\env\lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [20]:
# Case 3 - loss: 'modified_huber', alpha: 0.0001
model = \
    SGDClassifier(
    loss='modified_huber',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=None,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_pred, y_test))

print(classification_report(y_pred, y_test))

[[163 104]
 [  0   0]]
              precision    recall  f1-score   support

           0       1.00      0.61      0.76       267
           1       0.00      0.00      0.00         0

    accuracy                           0.61       267
   macro avg       0.50      0.31      0.38       267
weighted avg       1.00      0.61      0.76       267



c:\Users\ireti\Documents\GBC\AASD 4000\env\lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(
c:\Users\ireti\Documents\GBC\AASD 4000\env\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ireti\Documents\GBC\AASD 4000\env\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ireti\Documents\GBC\AASD 4000\env\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and b

**Observation**: Using a log loss and higher alpha value significantly reduced the model performance. However, using a _modified_huber_ loss function result in a jump in the model perfoormance.