<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 4 </p>

## Name: Iretioluwa Olawuyi

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

1. Using numpy arrays and slicing operations (:), define and print 
the following A, B, and C matrix:

In [9]:
A = np.array([[5, 2, 3],
            [6,1,3],
            [2,4,1]])

B = A[:2,:2]

C = A[1:,1:]

print("A = \n", A,"\n\nB = \n", B,"\n\nC = \n", C)

A = 
 [[5 2 3]
 [6 1 3]
 [2 4 1]] 

B = 
 [[5 2]
 [6 1]] 

C = 
 [[1 3]
 [4 1]]



 2. Define D matrix using numpy:

In [8]:
D = np.array([[4, -7, 4],
            [5,6,-1],
            [-4,2,5]])
print("D = \n", D)

D = 
 [[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


3. Use numpy matmulto calculate AD and also DA. Are they 
equal?

In [10]:
AD = np.matmul(A, D)

DA = np.matmul(D, A)

print("AD = \n", AD, "\n\n", "DA = \n", DA, "\n\nCheck - AD == DA?:", AD == DA)

AD = 
 [[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]] 

 DA = 
 [[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]] 

Check - AD == DA?: [[False False False]
 [False False False]
 [False False False]]


**Observation**: The result of matrix multiplication AD is not equal to DA

4. Manually calculate the determinant and inverse of B. Use 
numpy to calculate the same entities and confirm that your 
manual calculation agrees with your results from the jupyter
notebook

The determinant of a 2-by-2 matrix is:

$$ det(A) = | A | = 
\begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}
= (a \times d) - (b \times c)
$$

$$ det(B) = | B | = 
\begin{bmatrix}
5 & 2 \\
6 & 1 \\
\end{bmatrix}
= (5 \times 1) - (2 \times 6)
= 5 - 12 = -7
$$

The inverse of a 2-by-2 matrix is:
$$
{\begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}}^{-1}
=
\dfrac{1}{ad - bc}
\begin{bmatrix}
d & -b \\
-c & a \\
\end{bmatrix}
$$

$$
\equiv
{\begin{bmatrix}
5 & 2 \\
6 & 1 \\
\end{bmatrix}}^{-1}
=
\dfrac{1}{5 \times 1 - 2 \times 6}
\begin{bmatrix}
1 & -2 \\
-6 & 5 \\
\end{bmatrix}

= \dfrac{1}{-7} \times 
\begin{bmatrix}
1 & -2 \\
-6 & 5 \\
\end{bmatrix}

= 
\begin{bmatrix}
-0.143 & 0.286 \\
0.857 & -0.714 \\
\end{bmatrix}
$$

In [12]:
print(f"Inverse of matrix B is: \n{inv(B)}")
print(f"Determinant of matrix B is: {det(B)}")

Inverse of matrix B is: 
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]
Determinant of matrix B is: -6.999999999999999


5. Use numpy to calculate the inverse of D. Confirm that $DD^{-1}$
and $𝐷^{-1}D$ both are 3-by-3 identity matrices. Do you have any 
observations?

In [15]:
print(f"The inverse of Matrix D is: \n{inv(D)} \n")
print(f"D*D^-1 is: \n{np.matmul(D,inv(D))} \n")
print(f"D^-1*D is: \n{np.matmul(inv(D),D)} ")

The inverse of Matrix D is: 
[[ 0.07785888  0.10462287 -0.04136253]
 [-0.05109489  0.08759124  0.05839416]
 [ 0.08272506  0.0486618   0.14355231]] 

D*D^-1 is: 
[[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 6.93889390e-17  1.00000000e+00 -5.55111512e-17]
 [-1.38777878e-17 -8.32667268e-17  1.00000000e+00]] 

D^-1*D is: 
[[ 1.00000000e+00  6.93889390e-17  6.93889390e-18]
 [ 2.77555756e-17  1.00000000e+00 -2.08166817e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]] 


It is clear from the above that $DD^{-1}$ and $D^{-1}D$ both returns a 3-by-3 identity matrix